### ISSUE TITLE
Synching from \include’d subfile doesn’t work

### ISSUE THREAD

**Issue by towolf** [jaliste/gedit-synctex-plugin#2]
Complex documents often use a main file that is compiled and subfiles are included with `\input` or `\include` that only contain chapters.
The purpose often is to make is possible to comment out chapters to make compilation faster.

Without a way to track the main file synching from a subfile doesn’t work.

Not sure what the best way to implement this is. It should be simple.
- Vim uses a (usually empty) file to mark the main file: `main.tex.latexmain` alongside `main.tex` 
- The GeditLatexPlugin creates a hidden XML file
  .chapter.tex.properties.xml 
  <?xml version="1.0" ?><properties><property key="MasterFilename" value="../main.tex"/></properties>
  I find this method a bit clumsy and the mandatory selection dialog is a bit naggy.

Perhaps a menu item »☑ SyncTex main file« is appropriate under »Tools«. Dunno.

**Comment by towolf** [comment]
XML got lost, sorry. Should’ve wrappen it in a `pre`

**Comment by jaliste** [comment]
Yeah... there is basic support for backward search with several files, but you need to open the main file. However, forwardsearch is broken for include files. I will try to add support in case the main file is open, but I do want to keep the plugin simple, so not sure I want to add a main file selection. What could work, and I am open to implement is to add a modeline with the main_file, like adding the line %main:main.tex to the first line of a chapter file.

**Comment by jaliste** [comment]
Tobias, the plugin now lives on gedit-plugins repository of gnome server. So you can file bugs you find in Gnome Bugzilla.

**Comment by jaliste** [comment]
So I corrected the backward search and implemented the Forward search using a modeline. That is, you need to add the comment
% modeline: mainfile.tex 
to one of the first three lines of the included files so Forward search can work with them. Otherwise, it will be disabled.

**Comment by towolf** [comment]
Where did you commit that code? In gedit-plugins gnome_2_32 branch on git.gnome.org?

Also is this the intended modeline? Would that be correct?

`% modeline: ../Thesis.tex`

**Comment by towolf** [comment]
Perhaps this should be used in GediLatexPlugin too in place of the XML stub.

What about loading both plugins at the same time? Right now Ctrl-Click fires sync in both.

**Comment by jaliste** [comment]
Tobias, the modeline you describe is correct. I released gedit-plugins 2.31.5 from the gnome_2_32 branch, which contains the fixes I mentioned. All the development of the plugin is moved to gnome servers, so I will delete this repo soon. 

I will try to fix issues with gedit-latex plugin later. I still have not decided if make the plugins to cooperate or to implement synctex directly into the gedit-plugin. :)

**Comment by towolf** [comment]
I think you should change the modeline to something more semantically approriate.

What is included at the top of the file is _a_ modeline, but this particular modeline should have a specifier that mentions what it is for, like key-value pair.
I already have other modelines in my files. For example:

<pre>
% rubber: module xelatex
% vi:set fo=tcroq ft=tex fenc=latin1:
</pre>


perhaps `mainfile:` or `synctex_mainfile:` would be better.

**Comment by towolf** [comment]
Oh, just read the commit. That was just a typo on your part earlier.
It’s alright then.

**Comment by towolf** [comment]
Ok, more comments regarding modeline.
1. Putting a relative path like in my question doesn’t work if the current working dir of Gedit is somewhere else. Only absolute paths work for me.
2. It is common to allow to put modeline also at the end of the file. Even Gedit’s native modeline plugin for Emacs and Vim modelines allows this:
   <pre>
   /\* Parse vi(m) modelines.
   - Vi(m) modelines looks like this:
   -   - first form:   [text]{white}{vi:|vim:|ex:}[white]{options}
   -   - second form:  [text]{white}{vi:|vim:|ex:}[white]se[t] {options}:[text]
   - They can happen on the three first or last lines.
     */
     </pre>

Would this patch be ok?:

<pre>
From: Tobias Wolf <towolf@gmail.com>
Date: Fri, 13 Aug 2010 23:52:00 +0200
Subject: [PATCH] Modelines can be placed at the end of the file

---
 plugins/synctex/synctex/synctex.py |    3 ++-
 1 files changed, 2 insertions(+), 1 deletions(-)

diff --git a/plugins/synctex/synctex/synctex.py b/plugins/synctex/synctex/synctex.py
index 08690cf..ced11c3 100644
--- a/plugins/synctex/synctex/synctex.py
+++ b/plugins/synctex/synctex/synctex.py
@@ -101,7 +101,8 @@ class SynctexViewHelper:
 
     def get_output_file(self):
         file_output = None
-        for i in range(min(3,self._doc.get_line_count())):
+        line_count = self._doc.get_line_count()
+        for i in set(range(min(3,line_count)) + range(line_count)[-3:]):
             start = self._doc.get_iter_at_line(i)
             end = start.copy()
             end.forward_to_line_end()
-- 
1.7.1

</pre>

**Comment by towolf** [comment]
Another issue with relative paths
1. I open Gedit 
   - I load `Chapters/Methods.tex`
   - I ForwarSearch to Evince
   - I BackwarSearch from Evince
   - the plugin tries to load `Chapters/Chapters/Methods.tex`

The subfile is included with this command in the main file
`\include{Chapters/Methods}`

**Comment by jaliste** [comment]
The previous issues are fixed by the following patch. 
 http://pastebin.com/yezDApat
the latest issue I have not tested it yet.

**Comment by jaliste** [comment]
The latest issue is corrected by doing the following change to line 172. 
-            uri_input = self.gfile.get_parent().get_child(input_file).get_uri()
-            uri_input = self.out_gfile.get_parent().get_child(input_file).get_uri()

Could you test that with the two patches you get the expected behavior? Thanks for testing!

**Comment by towolf** [comment]
The relative paths work now. Thanks.

But now there is something very odd afoot. I managed to stall gedit at 100% CPU while using BackwardSearches.
- I have the PDF open and ctrl-click in Evince and the file is already open in Gedit: no problem
- I move to a page associated to a yet unopened source file: it tries to open twice (This file (/home/towolf/Thesis/Chapters/Methods.tex) is already open in another gedit window.)
- I move further to another place: It opens four instances all with the message
- I move even further: It opens 8 instances.

Screenshot:
http://imgur.com/65c27.png

I have no clue what this is caused by.

**Comment by jaliste** [comment]
Tobias, I think this is because the plugin search for existing instance only in one window. I am using a dict per window to track the open files, I guess I need to move the dict to the plugin instance. Thanks for testing

**Comment by jaliste** [comment]
Tobias, I think I fixed all remaining issues (Hopefully), I just released gedit-plugins 2.31.6 with all the fixes. Let me know if you can still reproduce your last issue in this version.

**Comment by towolf** [comment]
Thanks Jose, it works very nicely now. Make sure you put this prominently in the Gnome 2.32 ReleaseNotes. It’s a mighty fine example of desktop integration in Gnome.

On the topic of integration, the question is whether it should be integrated into the GeditLatexPlugin. I would say no. There will be users who want the one but not the other. Having it separate is a good approach, there just needs to be a minimum of integration, e.g., to enable the »-syntex=1« in the compiler.

I like the GLP overall, it saves time, but I see some issues:
- It’s kinda heavy with all the parsing and searching of the TEXMF tree. I have a test file of the novel Ulysses. Just to save the file and update the parser takes 8 seconds.
- It makes too many assumptions based on »standard usage«. 
  - I leave out the file extension in \input and \includegraphics because PDFTex then picks the file it wants or supports, i.e., .eps of .pdf. GLP raises these as issues and pesters me with messages while making things sluggish
  - It complains if I specify a \label and not use it elsewhere. I think that is excessive. It’s okay to warn about undefined references, but defining (yet) un_used_ references if not an issue.
  - Essentially I would like to be able to use a lighter GLP with less of the background intelligence that can get in the way.
  - I have a local Texlive2010 installation, but the GLP wants to search the packaged Texlive and it looks at kind of hardcoded paths.
  - The internal PDF view is kind of clumsy. I prefer external viewer. There should be a switch that defaults to external.
  - It doesn’t play well with the rest of Gedit and other plugins. It has home-grown solutions for snippets and completion and spell-check even though Gedit has better working modules that take care of this. They could even be integrated and used with the GLP. I raised this here: http://sourceforge.net/projects/gedit-latex/forums/forum/729149/topic/3481154
  - Finally it seems kinda stagnant lately, even though there’s a big refactoring effort on the horizon with libpeas.

**Comment by jaliste** [comment]
well, you should raise all these points in bugs in sf for glp. ;) I think I will integrate like this: I will add a preference in the GLP so it knows that you prefer to use external previewer. Then if external previewer is selected, it does not do anything on ctrl click. Thus, you can have both plugins installed and synctex will just work

**Comment by towolf** [comment]
And when you click a heading in the outline in the sidebar.
It keeps popping up  ಠ_ಠ
