### ISSUE TITLE
Doesn't play nice with the LaTeX plugin

### ISSUE THREAD

**Issue by sixtyfive** [jaliste/gedit-synctex-plugin#3]
Hi,

just installed Ubuntu 10.10 and compiled gedit-plugins-2.32. After finding out about pdflatex's --synctex switch, your plugin now works like a charm - thanks for writing it!

One issue I did notice is that the SyncTex and LaTeX plugins don't play along well with each other. E.g. when both are enabled, the built-in preview isn't working...

One AWESOME extra feature would be to trigger recompilation upon changing (or perhaps only upon saving) the .tex file. Not sure if that could easily be done or would actually belong into the LaTeX plugin instead, though.

Rock on!

**Comment by jaliste** [comment]
Hi, I am glad that plugin is working well for you. Please, if you have further issues you can submit bugs in bugzilla.gnome.org. The rationale for the Synctex plugin was to have the synctex support maintained inside a GNOME module (that is gedit-plugins). I need to patch gedit-latex plugin to make it aware that gedit-synctex exists and to change it's behaviour accordingly. About trigger recompilation, as I said, the idea of the plugin is to make it simple enough, and only manage the synctex part. All other things should be managed in the gedit-latex plugin.

**Comment by sixtyfive** [comment]
Thanks for the reply, jaliste! - In that case I'll file a feature request for the gedit-latex plugin.
